server:
  port: 8081

spring:
  application:
    name: CADASTRO-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eshop-service-registry:8761/eureka
    instance:
      hostname: localhost
