server:
  port: 9191

eureka:
  client:
    service-url:
      defaultZone: http://serviceregistry:8761/eureka/

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: cadastroservice
          uri: lb://cadastroservice
          predicates:
            - Path=/cadastro/**
        - id: produtosservice
          uri: lb://produtosservice
          predicates:
            - Path=/produtos/**
        - id: carrinhoservice
          uri: lb://carrinhoservice
          predicates:
            - Path=/carrinho/**
