# NÃO USAR O COMANDO docker-compose up -d

# ESTE ARQUIVO SERVE APENAS PARA GERAR AS IMAGENS DOCKER
# MAIS RAPIDAMENTE COM O COMANDO: docker-compose build

version: '3.9'

services:
  serviceregistry:
    image: serviceregistry
    build:
      context: ./service-registry/
      # dockerfile: service-registry/
    ports:
      - "8761:8761"
  
  apigateway:
    image: apigateway
    build:
      context: ./api-gateway/
      # dockerfile: api-gateway/Dockerfile
    ports:
      - "9191:9191"
    depends_on:
      - serviceregistry
  
  cadastroservice:
    image: cadastroservice
    build:
      context: ./cadastro-service/
      # dockerfile: cadastro-service/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - serviceregistry

  carrinhoservice:
    image: carrinhoservice
    build:
      context: ./carrinho-service/
      # dockerfile: carrinho-service/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - serviceregistry
  
  produtosservice:
    image: produtosservice
    build:
      context: ./produtos-service/
      # dockerfile: produtos-service/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - serviceregistry
