version: "3.9"

services:
  serviceregistry:
    image: serviceregistry
    build:
      context: ./service-registry/
    ports:
      - "8761:8761"
  
  apigateway:
    image: apigateway
    build:
      context: ./api-gateway/
    ports:
      - "9191:9191"
    depends_on:
      - serviceregistry
  
  cadastroservice:
    image: cadastroservice
    build:
      context: ./cadastro-service/
    ports:
      - "8081:8081"
    depends_on:
      - serviceregistry

  carrinhoservice:
    image: carrinhoservice
    build:
      context: ./carrinho-service/
    ports:
      - "8082:8082"
    depends_on:
      - serviceregistry
  
  produtosservice:
    image: produtosservice
    build:
      context: ./produtos-service/
    ports:
      - "8083:8083"
    depends_on:
      - serviceregistry
