version: '3.4'

services:
  eshop-service-registry:
    image: eshop-service-registry
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
  
  eshop-api-gateway:
    image: eshop-api-gateway
    build:
      context: ./api-gateway
    ports:
      - "9191:9191"
  
  eshop-cadastro:
    image: eshop-cadastro
    build:
      context: ./cadastro-service
    depends_on:
      - eshop-service-registry

  eshop-carrinho:
    image: eshop-carrinho
    build:
      context: ./carrinho-service
    depends_on:
      - eshop-service-registry
  
  eshop-produtos:
    image: eshop-produtos
    build:
      context: ./produtos-service
    depends_on:
      - eshop-service-registry
